databases:
  - name: faculty-analytics-db
    databaseName: faculty_analytics
    user: faculty_admin
    plan: free

services:
  - type: web
    name: faculty-analytics-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: faculty-analytics-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "anuguvaishnavireddy6@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "nswxqngdddphnsgj"
      - key: DEFAULT_FROM_EMAIL
        value: "Faculty Analytics Portal <anuguvaishnavireddy6@gmail.com>"
      - key: PYTHON_VERSION
        value: "3.12.0"
