# Generated by Django 6.0.7 on 2026-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0004_discussionpost_facultygoal_facultytimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='api_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grant',
            name='api_score',
            field=models.FloatField(default=0.0),
        ),
    ]
