# Generated by Django 6.0.7 on 2026-08-17 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_alter_historicaluser_role_and_more'),
        ('faculty_data', '0005_consultancy_api_score_grant_api_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('asset_type', models.CharField(choices=[('DATASET', 'Dataset'), ('CODE', 'Source Code'), ('PREPRINT', 'Pre-print Paper'), ('PRESENTATION', 'Presentation/Slides'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('file', models.FileField(upload_to='research_assets/')),
                ('is_public', models.BooleanField(default=True, help_text='Visible across the institution')),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
