# Generated by Django 6.0.7 on 2026-08-18 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0006_researchasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text='DOI Link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='issn_isbn',
            field=models.CharField(blank=True, help_text='ISSN/ISBN Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, help_text='e.g., 102-110', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EducationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g., B.Tech, M.Tech, Ph.D', max_length=100)),
                ('specialization', models.CharField(help_text='e.g., Computer Science and Engineering', max_length=255)),
                ('university', models.CharField(help_text='Institute or University Name', max_length=255)),
                ('year_of_passing', models.IntegerField()),
                ('percentage_cgpa', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year_of_passing'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, help_text='e.g. Assistant Professor', max_length=100, null=True)),
                ('aicte_id', models.CharField(blank=True, max_length=100, null=True)),
                ('jntuh_id', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working here', null=True)),
                ('experience_type', models.CharField(choices=[('TEACHING', 'Teaching'), ('INDUSTRY', 'Industry'), ('RESEARCH', 'Research')], default='TEACHING', max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
