# Generated by Django 6.0.7 on 2026-08-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0007_publication_doi_publication_issn_isbn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FDP', 'FDP Certificate'), ('WORKSHOP', 'Workshop Certificate'), ('STTP', 'STTP Certificate'), ('SEMINAR', 'Seminar Certificate'), ('CONFERENCE', 'Conference Certificate'), ('TRAINING', 'Training Certificate'), ('AWARD', 'Award & Recognition Certificate'), ('CONSULTANCY', 'Consultancy Proof'), ('PATENT', 'Patent Document'), ('PUBLICATION', 'Publication Proof'), ('OTHER', 'Other Academic Certificate')], default='FDP', max_length=50)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.CharField(default='2025-26', max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(help_text='e.g. Exam Coordinator, NSS Coordinator, IQAC Coordinator', max_length=255)),
                ('academic_year', models.CharField(default='2025-26', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
