# Generated by Django 6.0.7 on 2026-09-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0008_certificate_facultyrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IQACReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Computer Science & Engineering (Data Science) and AI&DS', max_length=255)),
                ('month', models.CharField(default='AUGUST', max_length=50)),
                ('year', models.CharField(default='2025', max_length=20)),
                ('academic_year', models.CharField(default='2025-26', max_length=50)),
                ('institution_name', models.CharField(default='AVN INSTITUTE OF ENGINEERING & TECHNOLOGY', max_length=255)),
                ('accreditation_details', models.CharField(default='Accredited by NAAC & NBA | An Autonomous Institute Affiliated to JNTU Hyderabad', max_length=255)),
                ('sections_data', models.JSONField(default=dict, help_text='Stores all 12 sections and customized tables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iqac_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('department', 'month', 'year')},
            },
        ),
    ]
