# Generated by Django 6.0.7 on 2026-09-28 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0009_iqacreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMonthlySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('month', models.CharField(default='AUGUST', max_length=50)),
                ('year', models.CharField(default='2025', max_length=20)),
                ('academic_year', models.CharField(default='2025-26', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20)),
                ('submission_data', models.JSONField(default=dict, help_text='Contains structured tables for FDPs, publications, events, etc.')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('faculty', 'month', 'year')},
            },
        ),
    ]
