# Generated by Django 6.0.7 on 2026-09-30 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0010_facultymonthlysubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymonthlysubmission',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='audit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='change_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_monthly_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_monthly_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultymonthlysubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facultymonthlysubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Approved & Locked')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='facultymonthlysubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
