from django.http import HttpResponse
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from django.db.models import Sum, Count
from django.utils import timezone
from datetime import timedelta

import openpyxl
from reportlab.pdfgen import canvas
import io
from faculty_data.models import Publication, Patent, Grant, Activity, Book
from core.models import User

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def dashboard_stats(request):
    user = request.user
    is_admin = user.role in ['ADMIN', 'HOD', 'IQAC']

    # Filter base querysets
    pubs = Publication.objects.all() if is_admin else Publication.objects.filter(faculty=user)
    patents = Patent.objects.all() if is_admin else Patent.objects.filter(faculty=user)
    grants = Grant.objects.all() if is_admin else Grant.objects.filter(faculty=user)

    # 1. KPI Cards Data
    total_pubs = pubs.count()
    total_patents = patents.count()
    total_grants = grants.aggregate(total=Sum('amount'))['total'] or 0
    total_faculty = User.objects.filter(role='FACULTY').count() if is_admin else 0

    # 2. Publication Trend (Last 5 Years)
    current_year = timezone.now().year
    trend_data = []
    for year in range(current_year - 4, current_year + 1):
        count = pubs.filter(year=year).count()
        trend_data.append({"name": str(year), "publications": count})

    # 3. Department Data (for Admins)
    dept_data = []
    if is_admin:
        # Assuming we just group by user's department
        departments = User.objects.exclude(department__isnull=True).exclude(department="").values('department').annotate(value=Count('id'))
        dept_data = [{"name": d['department'], "value": d['value']} for d in departments]

    # 4. Recent Activities
    # Combine recent publications, patents, etc. (Simplified: just fetch 5 recent pubs)
    recent_pubs = pubs.order_by('-created_at')[:5]
    recent_activities = []
    for p in recent_pubs:
        recent_activities.append({
            "id": p.id,
            "user": p.faculty.username,
            "dept": p.faculty.department or 'Unknown',
            "action": f"Published: {p.title[:30]}...",
            "time": p.created_at.strftime("%b %d, %Y")
        })

    return Response({
        "role": user.role,
        "kpis": {
            "total_faculty": total_faculty,
            "total_publications": total_pubs,
            "total_patents": total_patents,
            "total_grants_amount": total_grants
        },
        "trend_data": trend_data,
        "dept_data": dept_data,
        "recent_activities": recent_activities
    })

@api_view(['GET'])
@permission_classes([AllowAny])
def export_pdf(request):
    total_faculty = User.objects.filter(role='FACULTY').count()
    total_pubs = Publication.objects.count()
    total_patents = Patent.objects.count()

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)
    p.drawString(100, 800, "Faculty Performance Analytics Report")
    p.drawString(100, 780, "Generated by System")
    
    p.drawString(100, 750, f"Total Faculty: {total_faculty}")
    p.drawString(100, 730, f"Total Publications: {total_pubs}")
    p.drawString(100, 710, f"Total Patents: {total_patents}")
    
    p.showPage()
    p.save()
    buffer.seek(0)
    
    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    return response

@api_view(['GET'])
@permission_classes([AllowAny])
def export_excel(request):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Analytics Report"
    
    total_faculty = User.objects.filter(role='FACULTY').count()
    total_pubs = Publication.objects.count()
    total_patents = Patent.objects.count()

    ws.append(["Metric", "Value"])
    ws.append(["Total Faculty", total_faculty])
    ws.append(["Total Publications", total_pubs])
    ws.append(["Total Patents", total_patents])
    
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="report.xlsx"'
    wb.save(response)
    
    return response

@api_view(['GET'])
@permission_classes([AllowAny])
def export_compliance(request, report_type):
    # Generates specific compliance reports (NAAC, NBA, NIRF)
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = f"{report_type.upper()} Report"

    ws.append([f"{report_type.upper()} Compliance Data", ""])
    ws.append(["Category", "Count/Details"])
    
    # Generic live data fetching
    pubs = Publication.objects.count()
    patents = Patent.objects.count()
    grants = Grant.objects.aggregate(total=Sum('amount'))['total'] or 0

    if report_type == 'naac':
        ws.append(["3.1.1 - Grants Received (INR)", grants])
        ws.append(["3.2.2 - Workshops/Seminars (IPR/Industry-Academia)", Activity.objects.filter(category='GUEST_LECTURE').count()])
        ws.append(["3.3.2 - Research Publications", pubs])
        ws.append(["3.3.3 - Books and Chapters", Book.objects.count()])
    elif report_type == 'nba':
        ws.append(["Criterion 5 - Faculty Information and Contributions", ""])
        ws.append(["5.7 - Research and Development", f"{pubs} Pubs, {patents} Patents"])
    elif report_type == 'nirf':
        ws.append(["Research and Professional Practice (RPC)", ""])
        ws.append(["Publications (PUB)", pubs])
        ws.append(["Patents Published/Granted (PT)", patents])
    
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename="{report_type}_report.xlsx"'
    wb.save(response)
    
    return response

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def export_appraisal(request):
    user = request.user
    # Fetch user data
    pubs = Publication.objects.filter(faculty=user).count()
    patents = Patent.objects.filter(faculty=user).count()

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)
    p.drawString(100, 800, f"Annual Appraisal Report - {user.username}")
    p.drawString(100, 780, "Generated by System")
    
    p.drawString(100, 750, f"Total Publications this year: {pubs}")
    p.drawString(100, 730, f"Total Patents this year: {patents}")
    # Add more appraisal metrics as needed
    
    p.showPage()
    p.save()
    buffer.seek(0)
    
    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="appraisal_{user.username}.pdf"'
    return response

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def ai_insights(request):
    user = request.user
    
    pubs = Publication.objects.filter(faculty=user).count()
    patents = Patent.objects.filter(faculty=user).count()
    grants = Grant.objects.filter(faculty=user).count()
    
    # Calculate mock API score
    base_score = 50 + (pubs * 10) + (patents * 20) + (grants * 15)
    
    # Mock journal recommendations
    recommendations = [
        {"name": "IEEE Transactions on Engineering", "impact_factor": "4.5", "match": "High"},
        {"name": "Springer Nature Applied Sciences", "impact_factor": "3.8", "match": "Medium"},
        {"name": "Elsevier Computers & Education", "impact_factor": "5.1", "match": "High"}
    ]
    
    # Accreditation gap analysis
    gap_analysis = []
    if pubs < 5:
        gap_analysis.append("Need more Scopus indexed publications for NAAC Criterion 3.3.2.")
    if patents < 1:
        gap_analysis.append("Filing at least 1 patent will significantly boost NBA score under 5.7.")
    if grants == 0:
        gap_analysis.append("Applying for government grants (DST/AICTE) will improve NIRF ranking.")
        
    if not gap_analysis:
        gap_analysis.append("You are currently meeting the major accreditation benchmarks! Keep it up.")
        
    return Response({
        "api_score_prediction": min(base_score, 100),
        "journal_recommendations": recommendations,
        "gap_analysis": gap_analysis,
        "summary": f"Based on your profile ({pubs} publications, {patents} patents), your current projected API score is {min(base_score, 100)}. Focus on closing the identified gaps to maximize institutional scoring."
    })
